var e = /* @__PURE__ */ ((t) => (t.TpIntensivaoAntigoIcon = "tp-intensivao-antigo-icon", t.TpIntensivaoRIcon = "tp-intensivao-r-icon", t.TpIntensivaoR1Icon = "tp-intensivao-r1-icon", t.TpIntensivaoRMaisIcon = "tp-intensivao-rmais-icon", t.TpRMaisIcon = "tp-rmais-icon", t.TpNoPapoIcon = "tp-no-papo-icon", t.TpRacipeIcon = "tp-racipe-icon", t.TpRacIcon = "tp-rac-icon", t.TpVentilamedIcon = "tp-ventilamed-icon", t.TpMedimagemIcon = "tp-medimagem-icon", t.TpMedeletroIcon = "tp-medeletro-icon", t.TpCpmedIcon = "tp-cpmed-icon", t.TpMedmasterIcon = "tp-medmaster-icon", t.TpMedIcon = "tp-med-icon", t.TpMedcursoIcon = "tp-medcurso-icon", t.TpRevalidacaoIcon = "tp-revalidacao-icon", t.TpMedfocoIcon = "tp-medfoco-icon", t.TpMedatbIcon = "tp-medatb-icon", t.TpTedIcon = "tp-ted-icon", t.TpTegoIcon = "tp-tego-icon", t))(e || {}), r = /* @__PURE__ */ ((t) => (t.TpBymed = "tp-bymed", t.TpCpmedExpresso = "tp-cpmed-expresso", t.TpCpmedExtensivo = "tp-cpmed-extensivo", t.TpCpmedPremium = "tp-cpmed-premium", t.TpCpmedRevalida = "tp-cpmed-revalida", t.TpCpmed = "tp-cpmed", t.TpCpvent = "tp-cpvent", t.TpEditoraTemplarios = "tp-editora-templarios", t.TpFalaMedgrupo = "tp-fala-medgrupo", t.TpInstensivaoRMais = "tp-intensivao-r-mais", t.TpInstensivaoR1 = "tp-intensivao-r-um", t.TpInstensivaoRevalida = "tp-intensivao-revalida", t.TpInstensivao = "tp-intensivao", t.TpMed = "tp-med", t.TpMedcode = "tp-medcode", t.TpMedcurso = "tp-medcurso", t.TpMedeletro = "tp-medeletro", t.TpMederi = "tp-mederi", t.TpMedgrupo = "tp-medgrupo", t.TpMedicom = "tp-medicom", t.TpMedimagem = "tp-medimagem", t.TpMedMaster = "tp-medmaster", t.TpMedPos = "tp-medpos", t.TpMedReader = "tp-medreader", t.TpMedsoft = "tp-medsoft", t.TpMedwriters = "tp-medwriters", t.TpMedwritersEditora = "tp-medwriters-editora", t.TpMedycorp = "tp-medycorp", t.TpMedyklin = "tp-medyklin", t.TpMedyn = "tp-medyn", t.TpNoPapo = "tp-no-papo", t.TpPlantaoRecursos2 = "tp-plantao-recursos-2", t.TpPlantaoRecursos = "tp-plantao-recursos", t.TpRMaisCirurgia = "tp-r-mais-cirurgia", t.TpRMaisClinicaMedica = "tp-r-mais-clinica-medica", t.TpRMaisEndoscopia = "tp-r-mais-endoscopia", t.TpRMaisMaster = "tp-r-mais-master", t.TpRMaisMastologia = "tp-r-mais-mastologia", t.TpRMaisTego = "tp-r-mais-tego", t.TpRMaisTep = "tp-r-mais-tep", t.TpRMais = "tp-r-mais", t.TpR1 = "tp-r-um", t.TpRa = "tp-ra", t.TpRac = "tp-rac", t.TpRacipe = "tp-racipe", t.TpRm = "tp-rm", t.TpRMed = "tp-rmed", t.TpRMedCursos = "tp-rmed-cursos", t.TpTed = "tp-ted", t.TpTegoGinecologia = "tp-tego-ginecologia", t.TpTego = "tp-tego", t.TpVentilamed = "tp-ventilamed", t.TpZupper = "tp-zupper", t))(r || {});
const a = Object.values(e), i = Object.values(r), rt = [
  ...a,
  ...i
], at = a.map(
  (t) => `${t}`
), it = i.map(
  (t) => `${t}`
);
var p = /* @__PURE__ */ ((t) => (t.AcademicHat = "tp-academic-hat", t.Activity = "tp-activity", t.AddCircle = "tp-add-circle", t.AlertTriangle = "tp-alert-triangle", t.Anotar = "tp-anotar", t.ArrowBottomLeft = "tp-arrow-bottom-left", t.ArrowDownCircle = "tp-arrow-down-circle", t.ArrowDownFilled = "tp-arrow-down-filled", t.ArrowLeftCircle = "tp-arrow-left-circle", t.ArrowRightCircle = "tp-arrow-right-circle", t.ArrowTopRight = "tp-arrow-top-right", t.ArrowUpCircle = "tp-arrow-up-circle", t.ArrowUpFilled = "tp-arrow-up-filled", t.Avaliar = "tp-avaliar", t.AwardCheck = "tp-award-check", t.AwardTriumph = "tp-award-triumph", t.Award = "tp-award", t))(p || {}), d = /* @__PURE__ */ ((t) => (t.Baby = "tp-baby", t.Barcode = "tp-barcode", t.Bell = "tp-bell", t.Book = "tp-book", t.BookOpen = "tp-book-open", t.Bookmark = "tp-bookmark", t.Boleto = "tp-boleto", t.Briefcase = "tp-briefcase", t))(d || {}), u = /* @__PURE__ */ ((t) => (t.Calendar = "tp-calendar", t.Calculator = "tp-calculator", t.CalendarSpeed = "tp-calendar-speed", t.Camera = "tp-camera", t.Cards = "tp-cards", t.Carrinho = "tp-cart", t.CartaoResposta = "tp-cartao-resposta", t.ChartBar = "tp-chart-bar", t.ChartPie = "tp-chart-pie", t.Chat = "tp-chat", t.Chat2 = "tp-chat-2", t.Check = "tp-check", t.CheckCircle = "tp-check-circle", t.CheckCircle2 = "tp-check-circle-2", t.CheckSquare = "tp-check-square", t.Cheque = "tp-cheque", t.ChevronDown = "tp-chevron-down", t.ChevronHorizontal = "tp-chevron-horizontal", t.ChevronLeft = "tp-chevron-left", t.ChevronUp = "tp-chevron-up", t.ChevronRight = "tp-chevron-right", t.ChevronVertical = "tp-chevron-vertical", t.ChevronsRight = "tp-chevrons-right", t.ChevronsLeft = "tp-chevrons-left", t.Clip = "tp-clip", t.ClockPlay = "tp-clock-play", t.ClockSlow = "tp-clock-slow", t.Clock = "tp-clock", t.Coin = "tp-coin", t.ComentarioQuestao = "tp-comentario-questao", t.Compass = "tp-compass", t.Copy = "tp-copy", t.CornerBottomLeft = "tp-corner-bottom-left", t.Covid = "tp-covid", t.Cpf = "tp-cpf", t.CreditCard = "tp-credit-card", t.Credito = "tp-credito", t.Custom = "tp-custom", t))(u || {}), l = /* @__PURE__ */ ((t) => (t.Dircursiva = "tp-discursiva", t.Dislike = "tp-dislike", t.DivideSquare = "tp-divide-square", t.DolarSign = "tp-dollar-sign", t.Download = "tp-download", t.DragHandGesture = "tp-drag-hand-gesture", t.Drag = "tp-drag", t.Drugs = "tp-drugs", t))(l || {}), s = /* @__PURE__ */ ((t) => (t.Edit = "tp-edit", t.Expand = "tp-expand", t.Expand2 = "tp-expand-2", t.ExternalLink = "tp-external-link", t.Eye = "tp-eye", t.EyeOff = "tp-eye-off", t))(s || {}), v = /* @__PURE__ */ ((t) => (t.FaceHappy = "tp-face-happy", t.FaceSmile = "tp-face-smile", t.FaceMeh = "tp-face-meh", t.FaceFrown = "tp-face-frown", t.Faceterrible = "tp-face-terrible", t.FacebookTag = "tp-facebook-tag", t.Female = "tp-female", t.File = "tp-file", t.FileCheck = "tp-file-check", t.FileDollar = "tp-file-dollar", t.FileDuble = "tp-file-duble", t.FileSheet = "tp-file-sheet", t.FilePlus = "tp-plus", t.FileText = "tp-file-text", t.FileX = "tp-file-x", t.Filter = "tp-filter", t.Filter2 = "tp-filter-2", t.Filter3 = "tp-filter-3", t.FilterOff = "tp-filter-off", t.Flashcards = "tp-flashcards", t.Flask = "tp-flask", t.FolderPlus = "tp-folder-plus", t.Folder = "tp-folder", t.FontDecrease = "tp-font-decrease", t.FontIncrease = "tp-font-increase", t.FontSize = "tp-font-size", t))(v || {}), m = /* @__PURE__ */ ((t) => (t.Generico = "tp-generico", t.Gift = "tp-gift", t.Grid = "tp-grid", t.Grafico = "tp-grafico", t))(m || {}), h = /* @__PURE__ */ ((t) => (t.Headset = "tp-headset", t.Heart = "tp-heart", t.HeartFill = "tp-heart-fill", t.HelpCircle = "tp-help-circle", t.Home = "tp-home", t.Hospital = "tp-hospital", t.Hourglass = "tp-hourglass", t))(h || {}), c = /* @__PURE__ */ ((t) => (t.Ia = "tp-ia", t.IlustracaoTema = "tp-ilustracao-tema", t.IlustracaoTreino = "tp-ilustracao-treino", t.Image = "tp-image", t.Inbox = "tp-inbox", t.Info = "tp-info", t.Instagram = "tp-instagram", t.ImgAssimilacao = "img-assimilacao", t.ImgAutoFeedback = "img-autofeedback", t.ImgCovid19 = "img-covid-19", t.ImgOrganizacao = "img-organizacao", t.ImgOrientacoes = "img-orientacoes", t.ImgProvaIntegra = "img-prova-integra", t.ImgProvasIrmas = "img-provas-irmas", t.ImgSegredos = "img-segredos", t.ImgTopTemas = "img-top-temas", t))(c || {}), n = /* @__PURE__ */ ((t) => (t.Key = "tp-key", t.Keyboard = "tp-keyboard", t))(n || {}), O = /* @__PURE__ */ ((t) => (t.Layers = "tp-layers", t.List = "tp-list", t.ListStar = "tp-list-star", t.Light = "tp-light", t.Like = "tp-like", t.Linkedin = "tp-linkedin", t.Lock = "tp-lock", t.LogOut = "tp-log-out", t.Login = "tp-login", t))(O || {}), _ = /* @__PURE__ */ ((t) => (t.MoreVertical = "tp-more-vertical", t.MapPin = "tp-map-pin", t.MoreHorizontal = "tp-more-horizontal", t.Minus = "tp-minus", t.MinusCircle = "tp-minus-circle", t.Menu = "tp-menu", t.MedicalBag = "tp-medical-bag", t.Medrobot = "tp-medrobot", t.MemoriaDeAula = "tp-memoria-de-aula", t.Mail = "tp-mail", t.Mic = "tp-mic", t.Microphone = "tp-microphone", t.Microscope = "tp-microscope", t.Moon = "tp-moon", t.Medgrupo = "tp-medgrupo", t.Male = "tp-male", t))(_ || {}), C = /* @__PURE__ */ ((t) => (t.Numbers = "tp-numbers", t.NoPapo = "tp-nopapo", t.Notes = "tp-notes", t.NuvemOff = "tp-nuvem-off", t.NuvemOn = "tp-nuvem-on", t.Nuvem = "tp-nuvem", t))(C || {}), g = /* @__PURE__ */ ((t) => (t.OpenHandGesture = "tp-open-hand-gesture", t.Order = "tp-order", t.Order2 = "tp-order-2", t))(g || {}), k = /* @__PURE__ */ ((t) => (t.Passaporte = "tp-passaporte", t.ParkOutlineAlarm = "tp-park-outline-alarm", t.Paypal = "tp-paypal", t.Phone = "tp-phone", t.PictureInPictureActivate = "tp-picture-in-picture-activate", t.PictureInPictureDeactivate = "tp-picture-in-picture-deactivate", t.PinSlash = "tp-pin-slash", t.Pin = "tp-pin", t.PixSymbol = "tp-pix-symbol", t.Pix = "tp-pix", t.Plane = "tp-plane", t.PlayCircle = "tp-play-circle", t.Plus = "tp-plus", t.PlusCircle = "tp-plus-circle", t.PointerActive = "tp-pointer-active", t.PointerDefault = "tp-pointer-default", t.Pregnant = "tp-pregnant", t.Printer = "tp-printer", t.Prohibition = "tp-prohibition", t))(k || {}), M = /* @__PURE__ */ ((t) => (t.Qrcode = "tp-qrcode", t.QuestaoOld = "tp-questao-old", t))(M || {}), P = /* @__PURE__ */ ((t) => (t.RateRegular = "tp-rate-regular", t.RateExcelente = "tp-rate-excelente", t.RateBom = "tp-rate-bom", t.RateRuim = "tp-rate-ruim", t.Radio = "tp-radio", t.Reload = "tp-reload", t.Retomar = "tp-retomar", t.Repeat = "tp-repeat", t.RotateCcw = "tp-rotate-ccw", t.Riscar = "tp-riscar", t))(P || {}), w = /* @__PURE__ */ ((t) => (t.Save = "tp-save", t.Search = "tp-search", t.SearchX = "tp-search-x", t.Settings = "tp-settings", t.Send = "tp-send", t.Shrink = "tp-shrink", t.Slash = "tp-slash", t.Smart = "tp-smart", t.SmartphoneDevice = "tp-smartphone-device", t.SoundHigh = "tp-sound-high", t.Square = "tp-square", t.Star = "tp-star", t.Stethoscope = "tp-stethoscope", t.Sun = "tp-sun", t.Sus = "tp-sus", t))(w || {}), R = /* @__PURE__ */ ((t) => (t.Target = "tp-target", t.Thumbs = "tp-thumbs", t.ThumbsUp = "tp-thumbs-up", t.ThumbsDown = "tp-thumbs-down", t.TrendingDown = "tp-trending-down", t.TrendingUp = "tp-trending-up", t.Trash = "tp-trash", t.Type = "tp-type", t.TypeUnderline = "tp-type-underline", t.TypeSquare = "tp-type-square", t.TypePlus = "tp-type-plus", t.TypeDuble = "tp-type-duble", t.TypeMinus = "tp-type-minus", t))(R || {}), N = /* @__PURE__ */ ((t) => (t.User = "tp-user", t.UserCheck = "tp-user-check", t.UserScan = "tp-user-scan", t.UserX = "tp-user-x", t.Users = "tp-users", t.Upload = "tp-upload", t))(N || {}), o = /* @__PURE__ */ ((t) => (t.Video = "tp-video", t.Video2 = "tp-video-2", t.Virus = "tp-virus", t))(o || {}), j = /* @__PURE__ */ ((t) => (t.Whatsapp = "tp-whatsapp", t.WiFi = "tp-wi-fi", t.WiFiOff = "tp-wi-fi-off", t.WiFiOff2 = "tp-wi-fi-off-2", t))(j || {}), x = /* @__PURE__ */ ((t) => (t.X = "tp-x", t.XCircle = "tp-x-circle", t.XSquare = "tp-x-square", t))(x || {}), B = /* @__PURE__ */ ((t) => (t.Youtube = "tp-youtube", t))(B || {}), F = /* @__PURE__ */ ((t) => (t.Z = "tp-z", t.Zap = "tp-zap", t))(F || {});
const q = Object.values(p), E = Object.values(d), z = Object.values(u), Y = Object.values(l), f = Object.values(s), A = Object.values(v), H = Object.values(m), U = Object.values(h), G = Object.values(c), V = Object.values(n), K = Object.values(O), X = Object.values(_), b = Object.values(C), Q = Object.values(g), Z = Object.values(k), $ = Object.values(M), W = Object.values(P), J = Object.values(w), S = Object.values(R), y = Object.values(N), L = Object.values(o), D = Object.values(j), T = Object.values(x), I = Object.values(B), tt = Object.values(F), et = [
  ...q,
  ...E,
  ...z,
  ...Y,
  ...f,
  ...A,
  ...H,
  ...U,
  ...G,
  ...V,
  ...K,
  ...X,
  ...b,
  ...Q,
  ...Z,
  ...$,
  ...W,
  ...J,
  ...S,
  ...y,
  ...L,
  ...D,
  ...T,
  ...I,
  ...tt
], pt = et.map((t) => `${t}.svg`);
export {
  et as TP_ICONS,
  q as TP_ICONS_A,
  E as TP_ICONS_B,
  z as TP_ICONS_C,
  Y as TP_ICONS_D,
  f as TP_ICONS_E,
  A as TP_ICONS_F,
  H as TP_ICONS_G,
  U as TP_ICONS_H,
  G as TP_ICONS_I,
  V as TP_ICONS_K,
  K as TP_ICONS_L,
  X as TP_ICONS_M,
  b as TP_ICONS_N,
  Q as TP_ICONS_O,
  Z as TP_ICONS_P,
  $ as TP_ICONS_Q,
  W as TP_ICONS_R,
  J as TP_ICONS_S,
  pt as TP_ICONS_STORYBOOK,
  S as TP_ICONS_T,
  y as TP_ICONS_U,
  L as TP_ICONS_V,
  D as TP_ICONS_W,
  T as TP_ICONS_X,
  I as TP_ICONS_Y,
  tt as TP_ICONS_Z,
  rt as TP_SYMBOL_DEFS,
  a as TP_SYMBOL_DEFS_ICONS,
  at as TP_SYMBOL_DEFS_ICONS_STORYBOOK,
  i as TP_SYMBOL_DEFS_LOGOS,
  it as TP_SYMBOL_DEFS_LOGOS_STORYBOOK,
  p as TpIconA,
  d as TpIconB,
  u as TpIconC,
  l as TpIconD,
  s as TpIconE,
  v as TpIconF,
  m as TpIconG,
  h as TpIconH,
  c as TpIconI,
  n as TpIconK,
  O as TpIconL,
  _ as TpIconM,
  C as TpIconN,
  g as TpIconO,
  k as TpIconP,
  M as TpIconQ,
  P as TpIconR,
  w as TpIconS,
  R as TpIconT,
  N as TpIconU,
  o as TpIconV,
  j as TpIconW,
  x as TpIconX,
  B as TpIconY,
  F as TpIconZ,
  e as TpSymbolDefsIcons,
  r as TpSymbolDefsLogos
};
